### ISSUE TITLE
Safari doesn't support look-behind regex

### ISSUE THREAD

**Issue by qiyunzhu** [qiyunlab/binarena#33]
The assembly file title parse uses a look-behind regex (the `?<=` thing) ([here](https://github.com/qiyunlab/binarena/blob/c7ae72052d38ab79c5875c76d1d26a575757f55e/static/js/input.js#L585)). However, the Safari browser doesn't support it (see [details](https://caniuse.com/js-regexp-lookbehind)). It would be good to replace it with simpler regex.

**Comment by AbhinavChede** [comment]
Hi @qiyunzhu ,

I changed the regexes so it does not have the lookbehind regex

Thank you
Abhinav Chede

**Comment by qiyunzhu** [comment]
Perfectly addressed in #40
